services:
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  auth:
    build: ./auth
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/microservices
      - JWT_SECRET=SSHHhhhThisIsMySecret
      - API_KEY=TreesAreBeautiful

  admin:
    build: ./admin
    depends_on:
      - mongo
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/microservices
      - JWT_SECRET=SSHHhhhThisIsMySecret
      - API_KEY=TreesAreBeautiful

  reports:
    build: ./reports
    depends_on:
      - mongo
    ports:
      - "3002:3002"
    environment:
      - MONGO_URI=mongodb://mongo:27017/microservices
      - JWT_SECRET=SSHHhhhThisIsMySecret
      - API_KEY=TreesAreBeautiful

volumes:
  mongo-data:
