services:
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  auth:
    build: ./auth
    depends_on:
      - mongo
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/microservices

volumes:
  mongo-data:
