version: "3.8"
services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  notif-service:
    build: .
    container_name: notif-service
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - RUST_LOG=info

volumes:
  mongo-data:
